version: "3.8"

services:
    wordpress:
        build: .
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./docker/wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_USER: wordpress
            DB_PASSWORD: wordpress
            DB_NAME: wordpress

    db:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
            MYSQL_RANDOM_ROOT_PASSWORD: "1"

volumes:
    db_data:
